foo:
  bar: 1
  baz: qux
middleware:
  - request_identification

log:
  console:
    level: info
    format: text
  syslog:
    transport: udp
    server: localhost:514
    level: debug
metrics:
  prefix: dev
  inmem:
    interval_secs: 10
    retain_mins: 1
  statsd:
    server: localhost:514

amqp: amqp://guest:guest@localhost:5672/


